// Generated by gencpp from file mp_test/gesture.msg
// DO NOT EDIT!


#ifndef MP_TEST_MESSAGE_GESTURE_H
#define MP_TEST_MESSAGE_GESTURE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mp_test
{
template <class ContainerAllocator>
struct gesture_
{
  typedef gesture_<ContainerAllocator> Type;

  gesture_()
    : gesture()  {
    }
  gesture_(const ContainerAllocator& _alloc)
    : gesture(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _gesture_type;
  _gesture_type gesture;





  typedef boost::shared_ptr< ::mp_test::gesture_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mp_test::gesture_<ContainerAllocator> const> ConstPtr;

}; // struct gesture_

typedef ::mp_test::gesture_<std::allocator<void> > gesture;

typedef boost::shared_ptr< ::mp_test::gesture > gesturePtr;
typedef boost::shared_ptr< ::mp_test::gesture const> gestureConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mp_test::gesture_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mp_test::gesture_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mp_test::gesture_<ContainerAllocator1> & lhs, const ::mp_test::gesture_<ContainerAllocator2> & rhs)
{
  return lhs.gesture == rhs.gesture;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mp_test::gesture_<ContainerAllocator1> & lhs, const ::mp_test::gesture_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mp_test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mp_test::gesture_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mp_test::gesture_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mp_test::gesture_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mp_test::gesture_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mp_test::gesture_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mp_test::gesture_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mp_test::gesture_<ContainerAllocator> >
{
  static const char* value()
  {
    return "61f2a41b9e73483e6fa26641a58eaf74";
  }

  static const char* value(const ::mp_test::gesture_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x61f2a41b9e73483eULL;
  static const uint64_t static_value2 = 0x6fa26641a58eaf74ULL;
};

template<class ContainerAllocator>
struct DataType< ::mp_test::gesture_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mp_test/gesture";
  }

  static const char* value(const ::mp_test::gesture_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mp_test::gesture_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string gesture\n"
;
  }

  static const char* value(const ::mp_test::gesture_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mp_test::gesture_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gesture);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gesture_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mp_test::gesture_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mp_test::gesture_<ContainerAllocator>& v)
  {
    s << indent << "gesture: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.gesture);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MP_TEST_MESSAGE_GESTURE_H
